    
trigger:
- master

pool:
  vmImage: 'windows-2019' 

variables:
  dockerId: trapp91  
  imageName: 'containers-for-you-home:$(build.buildNumber)'

steps:
- script: |
    docker build -t $(dockerId)/$(imageName)-f src/Dockerfile src/Containers.ForYou
    docker login -u $(dockerId) -p $(dockerPassword) 
    docker push $(dockerId)/$(imageName)