version: "3"

services:
  web_app_service:
    image: sibica/web_app
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - HOMEPAGE_URL=http://homepage
    depends_on:
      - redis
    networks:
      - app-net

  redis:
    image: "redis"
    ports: 
      - "32768:6379"
  
networks:
  app-net:
    driver: bridge 