version: "3.7"

services:
  home:
    build: 
      dockerfile: src/Dockerfile
      context: .
    image: containers-for-you-home
    ports: 
      - 10900:80
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-windows-express
    environment:
      - ACCEPT_EULA=Y
      - sa_password=Uar2rhbV4aaa
    ports: 
      - 14332:1433